config/routes.rb
Bokushi::Application.routes.draw do
  get 'login' => 'entries#new'
  resources :timetables, :only => [:show,:index,:new,:create] do
    resources :entries, :only => [:new,:create,:edit,:update]
  end
  root :to => 'timetables#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :manage, :all
  end
end

app/models/entry.rb
class Entry < ActiveRecord::Base
  belongs_to :timetable
  attr_accessible :departure, :arrival, :vehicle
  validates_presence_of :vehicle, :timetable

  VEHICLES = [["Bus","bus"],["MAX","max"]]

  def arrival_time
    arrival && arrival.strftime("%H:%M")
  end
  def departure_time
    departure && departure.strftime("%H:%M")
  end

  def arrival=(s)
    if s.empty? || s.nil?
      s = departure + 40.minutes 
    elsif data = s.match(/^(\d+)(\d\d)$/) 
      s = "#{data[1]}:#{data[2]}"
    end
    self[:arrival] = s
  end
  def departure=(s)
    if data = s.match(/^(\d+)(\d\d)$/) 
      s = "#{data[1]}:#{data[2]}"
    end
    self[:departure] = s
  end

  class << self
    def vehicle(s)
      VEHICLES.select{|a,b| b==s}.flatten.first
    end
  end
end

app/models/timetable.rb
class Timetable < ActiveRecord::Base
  has_many :entries

  validates_presence_of :base,:destination

  CITIES = %w(Sendai Fukushima Yamagata)

  def route; "#{base} - #{destination}" end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include BasicApplicationController
  rescue_from CanCan::AccessDenied do |exception|
    if current_user
      redirect_to welcome_url, :alert => exception.message
    else
      redirect_to login_url, :alert => exception.message
    end
  end
  protect_from_forgery
  #def created(s); t("successes.created",:o=>t(s)) end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_filter :load_timetable, :only => [:new,:create,:edit,:update]

  def new
    @entry = @timetable.entries.build
  end

  def create
    @entry = @timetable.entries.build(params[:entry])
    if @entry.save
      redirect_to @timetable, :notice => created(:entry)
    else
      render :new
    end
  end

  def edit
    @entry = @timetable.entries.find(params[:id])
  end

  private

    def load_timetable
      @timetable = Timetable.find(params[:timetable_id])
    end
end

app/controllers/timetables_controller.rb
class TimetablesController < ApplicationController
  load_and_authorize_resource
  helper_method :sort_column, :sort_direction

  def show
    @entries = @timetable.entries.order(sort_column+" "+sort_direction)
    @entries = @entries.where(:vehicle => params[:vehicle]) if params[:vehicle]
    #@entries.select!{|e| e.vehicle == params[:vehicle]} if params[:vehicle]
    respond_to do |f|
      f.html
      f.json {render :json => @glossary.to_json}
    end
  end

  def index
  end

  def new
  end

  def create
    if @timetable.save
      redirect_to timetables_path, :notice => created(:timetable)
    else
      render :new
    end
  end

  private

    def sort_column
      Entry.column_names.include?(params[:sort]) ?  params[:sort] : 'departure'
    end
    def sort_direction
      %w(asc desc).include?(params[:direction]) ?  params[:direction] : 'asc'
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include BasicApplicationHelper
  include SortableColumnsHelper
end

app/helpers/basic_application_controller.rb
/home/johan/apps/basiq/app/helper/basic_application_controller.rb

app/helpers/basic_application_helper.rb
/home/johan/apps/basiq/app/helper/basic_application_helper.rb

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/sortable_columns_helper.rb
/home/johan/apps/basiq/app/helper/sortable_columns_helper.rb

app/helpers/timetables_helper.rb
module TimetablesHelper
end

app/views/entries/_form.html.erb
<%= semantic_form_for [@timetable,@entry] do |f| %>
  <%= f.input :departure, :as => :string, :input_html =>{:value => @entry.departure_time} %>
  <%= f.input :arrival, :as => :string, :input_html =>{:value => @entry.arrival_time} %>
  <%= f.input :vehicle, :as => :select, :collection => Entry::VEHICLES %>
  <%= f.submit %>
<% end %>

app/views/entries/edit.html.erb
<%= render 'form' %>

app/views/entries/new.html.erb
<%= semantic_form_for [@timetable,@entry] do |f| %>
  <%= f.input :departure, :as => :string %>
  <%= f.input :arrival, :as => :string %>
  <%= f.input :vehicle, :as => :select, :collection => Entry::VEHICLES %>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bokushi</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<% flash.each do |name,msg| %>
  <%= content_tag :div, msg, :id => "flash_#{name}" %>
<% end %>

<%= yield %>

</body>
</html>

app/views/timetables/index.html.erb
<%= title pt(:timetable) %>

<table>
  <% @timetables.each do |timetable| %>
    <tr>
      <td><%= link_to timetable.route, timetable %></td>
    </tr>
  <% end %>
</table>

<%= link_to new(:timetable), new_timetable_path %>

app/views/timetables/new.html.erb
<%= semantic_form_for @timetable do |f| %>
  <%= f.input :base, :as => :select, :collection => Timetable::CITIES %>
  <%= f.input :destination, :as => :select, :collection => Timetable::CITIES %>
  <%= f.submit %>
<% end %>

app/views/timetables/show.html.erb
<%= title @timetable.route %>

<% @entries.group_by(&:vehicle).each do |vehicle,entries| %>
  <%= minititle Entry::vehicle(vehicle) %>
  <table id="<%= vehicle %>">
    <tr>
      <th><%= sortable 'departure' %></th>
      <th><%= sortable 'arrival' %></th>
      <th></th>
    </tr>
    <% entries.each do |entry| %>
      <tr>
        <td><%= entry.departure_time %></td>
        <td><%= entry.arrival_time %></td>
        <td><%= link_to t(:edit), edit_timetable_entry_path(@timetable,entry) %></td>
      </tr>
    <% end %>
  </table>
<% end %>

<%= link_to new(:entry), new_timetable_entry_path(@timetable) %>